#ifndef IOHANDLERML_FF_HPP
#define IOHANDLERML_FF_HPP

#include "MlMPI.hpp"
#include "SemanticVersion.hpp"
#include "TagTranslator.hpp"
#include "debug.hpp"
#include "math.hpp"
#include "types.hpp"

#include <fstream>
#include <memory>
#include <string>
#include <vector>

namespace vaspml
{

/*******************************************************************************************
 * @class IoHandlerML_FF
 * @brief can read the ML_FF files created by VASP
 *
 * This class is used to read ML_FF files. Only newer versions of ML_FF files can be
 * read by the IoHandlerML_FF. There is semantic version check done to verify that the
 * ML_FF file can be read into VASPml. The class supports MPI support for io handling.
 * When VASPml is compiled with shared memory support the arrays which will be stored
 * in shared memory will only be read by rank 0. The class is responsible to distribute
 * any needed force field parameters defined in ML_FF files to other classes used
 * in VASPml.
 *******************************************************************************************/
class IoHandlerML_FF
{

  public:
    /**
     *constructor of IoHandlerML_FF
     *
     *@param fname file name from which the force field is read. File has to be in binary format
     */
    IoHandlerML_FF(void) = default;
    IoHandlerML_FF(const std::string& fname, const std::shared_ptr<MlMPI>& mpiIn = nullptr);
    void init(const std::string& fname, const std::shared_ptr<MlMPI>& mpiIn = nullptr);

    /**
     *reading force field parameters to the data map.
     *a description for the keys can be found in the function itself
     *or in the definition of the TagTranslator
     */
    void mainReader();

    /**
     *checking the version number of the machine learning force field.
     *
     * only newer versions of the ML_FF generated by vasp are supported
     */
    void check_version_number_header_and_binary();

    /**
     * getter for the whole data map read from the ML_FF file
     */
    const MultiTypeMap& get_data(void) const;

    /**
     * getting a scalar from the data map
     */
    template<typename T>
    T get_scalar(const std::string& key);

    /**
     * getting a std::vector<T> array from the data map
     */
    template<typename T>
    const std::vector<T>& get_array(const std::string& key);

    /**
     * getting a std::vector<std::vector<T>> array from the data map
     */
    template<typename T>
    const std::vector<std::vector<T>>& get_2Darray(const std::string& key);

    /**
     *accessing elements of the type map with operator [translator.get_InputTag("key")].
     *
     *The function will return a std::variant being capable of storing
     *any type used in the vasp_ml code
     */
    const MultiType& operator[](const std::string& key) const;

    /**
     *accessing elements of the type map with operator ("key").
     *
     *The function will return a std::variant being capable of storing
     *any type used in the vasp_ml code
     */
    const MultiType& operator()(const std::string& key) const;

    const TagTranslator& get_translator(void) const;
    /*******************************************************************************************
     * generate weights map for the weight factors of the descriptors.
     *******************************************************************************************/
    std::map<String, Real> generate_weightsMap(void) const;
    /*******************************************************************************************
     * make feature space map which is the product of number local reference configurations
     * times the number of descriptors
     *******************************************************************************************/
    std::map<String, ShVec1Int> generate_featureSpaceMap(void) const;
    /*******************************************************************************************
     * generate a dictionary which has descriptor type as key and the number of descriptors basis
     * functions as entry.
     *
     * The number of descriptors are stored per atom type in the force field.
     *******************************************************************************************/
    std::map<String, ShVec1Int> get_numberDescriptorsMap(void) const;
    /*******************************************************************************************
     * Compute maximum cutoff radius from different parts of the force field.
     *
     * @return Maximum cutoff radius.
     *******************************************************************************************/
    Real maxCutoffRadius() const;
    /*******************************************************************************************
     * convert units to machine learning code units
     * Angstroem      -> bohr
     * electron Volts -> hartree
     * ev/Angstroem   -> hartree / bohr
     *******************************************************************************************/
    void convertUnitsToAtomicUnits(void);
    /*******************************************************************************************
     * distribute arrays which are only read on the root node to the all other nodes.
     *******************************************************************************************/
    void distributeMemoryNonSharedMemory(void);

  private:
    /**
     * reading the header line of the ML_FF file
     *
     * header contains important parameters of the ML_FF
     * in human readable form
     */
    void read_header(void);
    /**
     *stores the human readable header line of the ML_FF
     *
     * gives short overview of some important ML_FF parameters
     */
    std::string header;
    /**
     *storing file name for input/output
     */
    std::string fileName;
    /**
     * data map contains key value pair for all data types found in ML_FF
     */
    MultiTypeMap data;
    /**
     *input file stream to read from the ML_FF file
     */
    std::ifstream input_stream;
    /**
     *translates the INCAR tags to code tags
     *
     * the values from the ML_FF files are read to the data map
     * and the values are stored with keys matching their INCAR tags.
     * In the code it is more useful to work with systematic tags which
     * can easily be looped over. The translator gives the translation between
     * the INCAR tags and the tags in the code. The translation is bidirectional
     */
    TagTranslator translator;
    /// Maximum version of ML_FF file this implementation can handle.
    const SemanticVersion versionMax = SemanticVersion(0, 2, 3);
    /// ML_FF version of input file.
    SemanticVersion versionIn;
    /*******************************************************************************************
     * mpi handle for the ML_FF reader. The ML_FF reader will read all smaller arrays on every
     * core.
     *
     * Only the arrays which might be stored in a shared memory fashion are only read at the
     * zero node. The array is then transfered to shared memory or broadcasted from the root
     * node to all others
     *******************************************************************************************/
    std::shared_ptr<MlMPI> mpiMain;
    /*******************************************************************************************
     * variable which decides which cores have to read the whole input.
     *
     * This variable checks if the reading is done by all cores. If the reading is done
     * by all cores will be decided based on the fact if there is an mpi communicator
     * passed to IoHandlerML_FF or if shared memory arrays will be used.
     * In case of usage of shared memory the root node will be the only reader.
     * In all other cases the all nodes will read in the whole ML_FF file.
     * the arrays which will depend on the variable are regression-coeff and
     * SHS2-2-body-reference-configs and SHS3-3-body-reference-configs
     *******************************************************************************************/
    bool rankReadsOn;
};

template<typename T>
T IoHandlerML_FF::get_scalar(const std::string& key)
{
    VASPML_DEBUG_L1(
        if (data.count(translator.get_InputTag(key)) == 0)
        {
            throw std::runtime_error("ERROR in T IoHandlerML_FF::get_scalar(const std::string key) "
                                     "\n      key does not exist in dictionary data");
        }
    );

    return data[translator.get_InputTag(key)].cget<T>();
}

template<typename T>
const std::vector<T>& IoHandlerML_FF::get_array(const std::string& key)
{
    VASPML_DEBUG_L1(
        if (data.count(translator.get_InputTag(key)) == 0)
        {
            throw std::runtime_error(
                "ERROR in const std::vector<T>& IoHandlerML_FF::get_array(const std::string key) \n"
                "      key does not exist in dictionary data");
        }
    );

    return data[translator.get_InputTag(key)].dcget<std::shared_ptr<std::vector<T>>>();
}

template<typename T>
const std::vector<std::vector<T>>& IoHandlerML_FF::get_2Darray(const std::string& key)
{
    VASPML_DEBUG_L1(
        if (data.count(translator.get_InputTag(key)) == 0)
        {
            throw std::runtime_error(
                "ERROR in const std::vector<std::vector<T>>& IoHandlerML_FF::get_2Darray\n"
                "(const std::string key): key does not exist in dictionary data");
        }
    );

    return data[translator.get_InputTag(key)].dcget<std::shared_ptr<std::vector<std::vector<T>>>>();
}

} // namespace vaspml

#endif
