#ifndef KERNEL_HPP
#define KERNEL_HPP

#include "ArrayResizing.hpp"
#include "DescriptorCollector.hpp"
#include "Frame.hpp"
#include "IoHandlerML_FF.hpp"
#include "Linalg.hpp"
#include "MlMPI.hpp"
#include "ParallelEnvironemt.hpp"
#include "ShmemArray.hpp"
#include "TypeMap.hpp"
#include "types.hpp"

#include <map>
#include <memory>

namespace vaspml
{

std::map<String, std::shared_ptr<ShmemArray2DVariableLen<Real>>> generate_ShmemArrayMap(
    const std::map<String, Real>&      weights,
    const std::map<String, ShVec1Int>& featureSpaceSize,
    const std::shared_ptr<MlMPI>&      mpiIn);

/*******************************************************************************************
 * @class Kernel
 * @brief this class is a purely virtual base class for any Kernel implementation
 *
 * The class implements the minimum functions which are needed for defining a Kernel matrix
 * expressed in terms of descriptors which are derived classes of the Descriptor virtual
 * base class.
 *******************************************************************************************/
class Kernel
{

  public:
    /*******************************************************************************************
     * default construction of Kernel class.
     *
     * @note class is not usable in this state, but can be transformed into
     * an usable state by calling Kernel::Init( const IoHandlerML_FF& inputParameters,
     * const std::shared_ptr<MlMPI>& mpiIn = nullptr,const ShVec2Real& kernelMatrix = nullptr )
     *******************************************************************************************/
    Kernel(void) = default;
    /*******************************************************************************************
     * construct base Kernel class
     *
     * @param inputParameters input parameters from force field file generated by vasp
     * @param mpiIn class which will be used to make a shared memory and internode communicator for
     *ShmemArray
     * @param kernelMatrix by supplying the memory can be managed from the outside
     *******************************************************************************************/
    Kernel(const IoHandlerML_FF&         inputParameters,
           const std::shared_ptr<MlMPI>& mpiIn = nullptr,
           const ShVec2Real&             kernelMatrix = nullptr,
           const ExecutionPolicy         algoExecution = ExecutionPolicy::cpuSingleCore);
    /*******************************************************************************************
     * Destructor, required because this is an abstract base class.
     *******************************************************************************************/
    virtual ~Kernel() = default;
    /*******************************************************************************************
     * transfer class from default constructed state into a state which can be used to compute
     * kernels
     *
     * @param inputParameters input parameters from force field file generated by vasp
     * @param mpiIn class which will be used to make a shared memory and internode communicator
     * for ShmemArray
     * @param kernelMatrix by supplying the memory can be managed from the outside
     *******************************************************************************************/
    void init(const IoHandlerML_FF&         inputParameters,
              const std::shared_ptr<MlMPI>& mpiIn = nullptr,
              const ShVec2Real&             kernelMatrix = nullptr,
              const ExecutionPolicy         algoExecution = ExecutionPolicy::cpuSingleCore);
    /*******************************************************************************************
     * updating the Kernel class by computing the kernelMatrix
     *
     * @param frame describes current atomic structure with help of descriptors DescriptorSHS2,
     * DescriptorSHS3
     *
     * routine performs the following steps:
     * |step | action                                                |
     * |:----|:------------------------------------------------------|
     * | 1   | resize kernelMatrix if necessary                      |
     * | 2   | set kernelMatrix to zero                              |
     * | 3   | compute descriptorCollector from supplied frame class |
     * | 4   | compute kernelMatrix                                  |
     *
     *******************************************************************************************/
    void updateKernel(const Frame& frame);
    /*******************************************************************************************
     * Get local reference configurations described in descriptor space of 2-body (DescriptorSHS2),
     * 3body (DescriptorSHS3),... descriptors.
     *
     * Descriptors are described in terms of DescriptorSHS2, DescriptorSHS3...
     * map can chose from SHS2-2-body SHS3-3-body; map strings are defined in constants.hpp
     *******************************************************************************************/
    const std::map<String, std::shared_ptr<ShmemArray2DVariableLen<Real>>>
    get_descriptorsRefConfs() const;
    /*******************************************************************************************
     * getter for number of local reference configurations
     *******************************************************************************************/
    ShVec1Int get_numberLocalRefConfs(void) const;
    /*******************************************************************************************
     * getter for number of Descriptors ( basis set size )
     *******************************************************************************************/
    const std::map<String, ShVec1Int>& get_numberDescriptors(void) const;
    /*******************************************************************************************
     * getting the feature space size which is the product of number
     * descriptors times local reference configurations
     *******************************************************************************************/
    const std::map<String, ShVec1Int>& get_featureSpaceSize(void) const;
    /*******************************************************************************************
     * getter for descriptor weights ( not regression coefficients )
     *
     * map entries belong to SHS2-2-body (DescriptorSHS2), SHS3-3-body (DescriptorSHS3)
     *******************************************************************************************/
    const std::map<String, Real>& get_weights(void) const;
    /*******************************************************************************************
     * getter for kernelMatrix
     *
     * @note kernelMatrix will be overwritten by the kernel function defined in the child
     * classes, as for example KernelPolynomial
     *
     * dimensions of Kernel matrix are atom types as first dimension and, and a combined index
     * of atoms per type times number local reference configurations
     * @f$\mathbf{K}_{iB}=\mathbb{R}^{N_{types} \times (N_{atoms\ per\ type}\times N_{local\ ref
     *\ confs})}@f$
     *******************************************************************************************/
    const ShVec2Real& get_kernelMatrix(void) const;
    /*******************************************************************************************
     * get the number of atoms per type belonging to structure from which kernelMatrix was computed
     *******************************************************************************************/
    const ShVec1Int& get_nAtomsType(void) const;
    /*******************************************************************************************
     * return type map which maps force field types to structure types and vice versa
     *******************************************************************************************/
    std::shared_ptr<const TypeMap> get_typeMap(void) const;
    /*******************************************************************************************
     * give raw pointer to where kernelMatrix for certain atom of certain type starts
     *
     * @param type atom type for which pointer is retrieved
     * @param atomInType atom number of certain type for which pointer is retrieved
     *
     * @note the length of the slice for a certain atom of a type is determined by
     * numberLocalRefConfs[ typeMap -> toType( type ) ]
     *******************************************************************************************/
    const Real* get_kernelMatrixAtom(std::size_t type, std::size_t atomInType) const;
    /*******************************************************************************************
     * Computing derivative of kernel.
     *
     * formally this can be written as
     * @f[\sum_{B}w_{B}\frac{\partial K(\hat{\mathbf{X}}_{i},\hat{\mathbf{X}}_{B})}
     * {\partial \hat{\mathbf{X}}_{i} }@f]
     * for details about implementation please check the derived classes as for
     * example KernelPolynomial
     *******************************************************************************************/
    virtual void computeDerivativeKernel(Vec1Real&          derivativeMatrix,
                                         Vec1Real&          forceVector,
                                         const Real*        descriptorsRefConfsWeighted,
                                         const Real*        regressionCoefficients,
                                         const std::size_t& typeStruc,
                                         const std::size_t& typeForceField,
                                         const String&      key) const = 0;
    /*******************************************************************************************
     * getter for descriptorCollection stores normalized descriptors and neighbor Lists
     *******************************************************************************************/
    const DescriptorCollector& get_descriptorCollection(void) const;

  private:
    /*******************************************************************************************
     * setting up the descriptor collector class;
     *
     * This class normalizes the supplied descriptors and stores them in the proper format for the
     * Kernel class. The format is [type][ number atoms per type x number of descriptors for type ]
     *******************************************************************************************/
    void setUpDescriptorCollector(
        const std::map<String, std::shared_ptr<Descriptor>>& structureDescriptors);
    /*******************************************************************************************
     * compute the Kernel matrix for the supplied descriptors stored in descriptor collection
     * Kernel matrix is defined by a kernel function @f$ K(:,\hat{\mathbf{X}}_{B}) @f$ as
       @f[
          K_{iB} =  K(\hat{\mathbf{X}}_{i},\hat{\mathbf{X}}_{B})
       @f]
     * the @f$ \hat{\mathbf{X}}_{i} @f$ denotes the description of a certain atom i
     * within it's cutoff radius by the use of the descriptors stored in the descriptorCollector
     * object.
     *******************************************************************************************/
    void compute_kernelMatrix(void);
    /*******************************************************************************************
     * allocating kernel matrix as [types][ atoms per type x number reference configurations per
     *type ]
     *
     * also sets matrix elements to zero by using std::fill after doing the resize
     *******************************************************************************************/
    void allocate_kernelMatrix(const Vec1Int& nAtomPerType);
    void resizeKernelMatrixGPU(const Vec1Int& nAtomPerType);
    void compute_kernelMatrixDim(const Vec1Int& nAtomPerType);
    /*******************************************************************************************
     * fill shared memory arrays with descriptors from the reference configurations
     * of a pre trained force field
     *
     * @param inputParameters reader of the ML_FF file has to be supplied to extract reference
     * configurations
     *
     * @note the shared memory array has to be prepared with proper size before calling this
     *function
     * @note to be able to use shared memory a mpiIn has to be supplied in the constructor
     *******************************************************************************************/
    void fillDescriptor(const IoHandlerML_FF& inputParameters);

  protected:
    /*******************************************************************************************
     * storing weights for 2-body (DescriptorSHS2),3-body(DescriptorSHS3)...
     * descriptors ( are not regression coefficients )
     *******************************************************************************************/
    std::map<String, Real> weights;
    /// number of local reference configurations per force field type
    ShVec1Int numberLocalRefConfs;
    /// storing the number of basis functions for 2-body, 3-body... terms
    std::map<String, ShVec1Int> numberDescriptors;
    /*******************************************************************************************
     * feature space size for 2-body, 3-body...
     *
     * featureSpace size is the number of number of local reference configurations times
     * number of basis functions for a certain descriptor. featureSpaceSize can be retrieved
     * per descriptor. The type of descriptor is defined by the string of the map
     *******************************************************************************************/
    std::map<String, ShVec1Int> featureSpaceSize;
    /*******************************************************************************************
     * local reference configurations described in descriptor space of 2-body, 3body...
     * descriptors map can chose from 2-body and 3-body... descriptors by keys
     * defined in constants.hpp
     *******************************************************************************************/
    std::map<String, std::shared_ptr<ShmemArray2DVariableLen<Real>>> descriptorsRefConfs;
    /*******************************************************************************************
     * collector class to store all possible dscriptors.
     *
     * @note for the here used kernel the desciptors in the collector class
     * have to be type ordered
     *******************************************************************************************/
    std::shared_ptr<DescriptorCollector> descriptorCollection;
    /*******************************************************************************************
     * Stores kernel matrix.
     *
     * Kernel matrix is defined by a kernel function @f$ K(:,\hat{\mathbf{X}}_{B}) @f$ as
     *
     * @f[
          K_{iB} =  K(\hat{\mathbf{X}}_{i},\hat{\mathbf{X}}_{B})
     * @f]
     * the @f$ \hat{\mathbf{X}}_{i} @f$ denotes the description of a certain atom i
     * within it's cutoff radius by the use of the descriptors stored in the descriptorCollector
     * object.
     *
     * The kernelMatrix has structure atom types as first index and the
     * second index is a combination of atoms per type in the structure
     * times the local reference configurations
     *******************************************************************************************/
    ShVec2Real      kernelMatrix;
    Vec1Size_t      kernelMatrixDim;
    ArrayResizing2D kernelMatrixSize;
    /*******************************************************************************************
     * typeMap which assigns the force field atom types to the types in the structure and vice versa
     *******************************************************************************************/
    std::shared_ptr<const TypeMap> typeMap;
    /*******************************************************************************************
     * number of atoms per type in structure
     *******************************************************************************************/
    ShVec1Int             nAtomsPerType;
    ExecutionPolicy       algoExecution;
    linalg::LinalgContext linalgContext;
};

} //namespace vaspml

#endif
