#!/bin/bash
#PBS -N topo_wcc
#PBS -q cmt
#PBS -l select=1:ncpus=28:mpiprocs=28:mem=200gb
#PBS -l walltime=48:00:00
#PBS -j oe
set -euo pipefail
set +u
source /etc/profile.d/modules.sh
module load pbspro oneapi-2024.2/compiler/2024.2.1 oneapi-2024.2/mkl/latest oneapi-2024.2/mpi/latest hdf/5/1.14.1-2_intel2021
set -u
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export PYTHONDONTWRITEBYTECODE=1

cd '/cmt2/lniu6305/H-Beryllene_20250718/9.0_topology/tools'
'/cmt2/lniu6305/H-Beryllene_20250718/9.0_topology/packages/soc_topology/venv/bin/python' -B wcc_driver.py '/cmt2/lniu6305/H-Beryllene_20250718/9.0_topology/b-Beryllene_b' '/cmt2/lniu6305/H-Beryllene_20250718/9.0_topology/packages/soc_topology' --gap-stage gap_refine_1 --gap-stage gap_refine_2 > '/cmt2/lniu6305/H-Beryllene_20250718/9.0_topology/b-Beryllene_b/wcc_driver.log' 2>&1
